# Generated by Django 6.0.2 on 2026-02-07 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_profile_target_savings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('owner', 'category', 'currency')},
        ),
    ]
